import * as THREE from 'three';
import { RULES, getLevel, ports, indexOf } from './data.js';
import { createCellModel, createCisternModel, createCursorModel, createFlowerModel, createPacketModel, createPipeModel, createRockModel, disposeModel, palette, routePoint, pointSplitter } from './models.js';

const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
const gridWorld = (x, z) => ({ x: (x - 3) * RULES.cellSize, z: (z - 3) * RULES.cellSize });
const dirVector = (dir) => [{ x: 0, z: -1 }, { x: 1, z: 0 }, { x: 0, z: 1 }, { x: -1, z: 0 }][((Number(dir) % 4) + 4) % 4];

function rendererProbe() {
  let name = '';
  try {
    const probeCanvas = document.createElement('canvas'); const gl = probeCanvas.getContext('webgl') || probeCanvas.getContext('experimental-webgl'); const ext = gl?.getExtension('WEBGL_debug_renderer_info'); name = ext ? gl.getParameter(ext.UNMASKED_RENDERER_WEBGL) : gl?.getParameter(gl.RENDERER) || '';
  } catch (_) {}
  return /swiftshader|llvmpipe|software|mesa/i.test(`${name} ${globalThis.navigator?.userAgent || ''}`);
}

class RainScene {
  constructor(host) {
    this.host = host; this.canvas = host?.tagName === 'CANVAS' ? host : host?.querySelector?.('canvas') || document.createElement('canvas'); if (host?.tagName !== 'CANVAS') host?.appendChild?.(this.canvas);
    const software = rendererProbe(); this.renderer = new THREE.WebGLRenderer({ canvas: this.canvas, antialias: !software, powerPreference: 'high-performance' }); this.software = software; this.pixelBudget = software ? 400000 : 1500000; this.renderer.outputColorSpace = THREE.SRGBColorSpace; this.renderer.shadowMap.enabled = !software;
    this.scene = new THREE.Scene(); this.scene.background = this.makeSky(); this.scene.fog = new THREE.Fog(0x9cb6ad, 18, 34); this.world = new THREE.Group(); this.scene.add(this.world); this.board = new THREE.Group(); this.board.name = 'greenhouse-board'; this.world.add(this.board); this.buildBoardFrame(); this.markShadows(this.board); this.addLights();
    this.camera = new THREE.OrthographicCamera(-6, 6, 6, -6, .1, 60); this.scene.add(this.camera); this.cellBatch = this.createCellInstances(); this.world.add(this.cellBatch); this.levelGroup = new THREE.Group(); this.world.add(this.levelGroup); this.levelId = null; this.level = null; this.signature = ''; this.fixed = new Map(); this.pipeMeshes = new Map(); this.splitterMeshes = new Map(); this.flowerMeshes = new Map(); this.packetMeshes = new Map(); this.effects = []; this.elapsed = 0; this.frame = 0; this.lastEvents = null; this.cursorGhost = null; this.hintGhost = null; this.cursorOutline = this.makeCursorOutline(); this.world.add(this.cursorOutline); this.resize(); this.resizeObserver = globalThis.ResizeObserver ? new ResizeObserver(() => this.resize()) : null; this.resizeObserver?.observe(host || this.canvas);
  }
  createCellInstances() {
    const template = createCellModel();
    this.cellTemplate = template;
    const batch = new THREE.Group();
    batch.name = 'cell-instances';
    const dummy = new THREE.Object3D();
    const cells = RULES.gridSize * RULES.gridSize;
    for (const child of template.children) {
      if (!child.isMesh) continue;
      const instances = new THREE.InstancedMesh(child.geometry, child.material, cells);
      instances.name = `cells-${child.name}`;
      instances.castShadow = !this.software && !child.material.transparent;
      instances.receiveShadow = !child.material.transparent;
      let i = 0;
      for (let z = 0; z < RULES.gridSize; z++) for (let x = 0; x < RULES.gridSize; x++) {
        const p = gridWorld(x, z);
        dummy.position.set(p.x + child.position.x, child.position.y, p.z + child.position.z);
        dummy.rotation.copy(child.rotation);
        dummy.scale.copy(child.scale);
        dummy.updateMatrix();
        instances.setMatrixAt(i++, dummy.matrix);
      }
      instances.instanceMatrix.needsUpdate = true;
      batch.add(instances);
    }
    return batch;
  }
  makeSky() { if (typeof document === 'undefined') return new THREE.Color(0x93b0aa); const canvas = document.createElement('canvas'); canvas.width = 32; canvas.height = 32; const ctx = canvas.getContext('2d'); const gradient = ctx.createLinearGradient(0, 0, 0, 32); gradient.addColorStop(0, '#203d52'); gradient.addColorStop(.52, '#78a99e'); gradient.addColorStop(1, '#e6c78d'); ctx.fillStyle = gradient; ctx.fillRect(0, 0, 32, 32); const texture = new THREE.CanvasTexture(canvas); texture.colorSpace = THREE.SRGBColorSpace; this.skyTexture = texture; return texture; }
  addLights() { const hemi = new THREE.HemisphereLight(0xf4e3c8, 0x4b665d, 1.9); this.scene.add(hemi); const key = new THREE.DirectionalLight(0xffe1ad, 2.1); key.position.set(7, 13, 8); key.castShadow = !this.software; key.shadow.mapSize.set(768, 768); key.shadow.camera.left = -8; key.shadow.camera.right = 8; key.shadow.camera.top = 8; key.shadow.camera.bottom = -8; key.shadow.camera.near = .5; key.shadow.camera.far = 45; key.shadow.bias = -.0004; this.scene.add(key); this.scene.add(key.target); this.keyLight = key; }
  makeCursorOutline() { const geometry = new THREE.BufferGeometry(); geometry.setAttribute('position', new THREE.Float32BufferAttribute([-.61, .04, -.61, .61, .04, -.61, .61, .04, .61, -.61, .04, .61], 3)); const outline = new THREE.LineLoop(geometry, new THREE.LineBasicMaterial({ color: palette.gold, transparent: true, opacity: .9 })); outline.name = 'cursor-selection-outline'; outline.visible = false; return outline; }
  buildBoardFrame() { const base = new THREE.Mesh(new THREE.BoxGeometry(9.8, .24, 9.8), new THREE.MeshStandardMaterial({ color: palette.mossDark, roughness: .95 })); base.position.y = -.24; this.board.add(base); base.receiveShadow = !this.software; const rimMat = new THREE.MeshStandardMaterial({ color: palette.ceramicShadow, roughness: .85 }); for (const [x, z, w, d] of [[0, -4.52, 9.2, .16], [0, 4.52, 9.2, .16], [-4.52, 0, .16, 9.2], [4.52, 0, .16, 9.2]]) { const rim = new THREE.Mesh(new THREE.BoxGeometry(w, .07, d), rimMat); rim.position.set(x, -.08, z); this.board.add(rim); } const frameMat = new THREE.MeshStandardMaterial({ color: palette.copper, metalness: .58, roughness: .3 }); for (const [x, z] of [[-4.8, -4.8], [4.8, -4.8], [-4.8, 4.8]]) { const post = new THREE.Mesh(new THREE.CylinderGeometry(.06, .08, 1.4, 8), frameMat); post.position.set(x, .7, z); this.board.add(post); } for (const [x, z, sx, sz] of [[0, -4.8, 9.6, .07], [-4.8, 0, .07, 9.6]]) { const beam = new THREE.Mesh(new THREE.BoxGeometry(sx, .08, sz), frameMat); beam.position.set(x, 1.4, z); this.board.add(beam); } }
  markShadows(root) { root.traverse((object) => { if (!object.isMesh) return; const transparent = object.material?.transparent; object.castShadow = !this.software && !transparent; object.receiveShadow = !transparent; }); }
  clearLevel() { if (this.levelGroup) { this.levelGroup.children.slice().forEach((child) => { this.levelGroup.remove(child); disposeModel(child); }); } this.effects.forEach((effect) => { this.world.remove(effect.root); disposeModel(effect.root); }); this.effects.length = 0; this.fixed.clear(); this.pipeMeshes.clear(); this.splitterMeshes.clear(); this.flowerMeshes.clear(); this.packetMeshes.forEach((mesh) => { this.world.remove(mesh); disposeModel(mesh); }); this.packetMeshes.clear(); if (this.cursorGhost) { this.world.remove(this.cursorGhost); disposeModel(this.cursorGhost); } if (this.hintGhost) { this.world.remove(this.hintGhost); disposeModel(this.hintGhost); } this.cursorGhost = null; this.hintGhost = null; this.signature = ''; this.lastEvents = null; }
  fixedKey(x, z) { return `${x},${z}`; }
  buildLevel(levelId, board = []) { const level = getLevel(levelId); if (!level) return; this.clearLevel(); this.level = level; this.levelId = levelId; const fixed = Array.isArray(level.fixed) ? level.fixed : []; for (const tile of fixed) { this.fixed.set(this.fixedKey(tile.x, tile.z), tile); const p = gridWorld(tile.x, tile.z); if (tile.kind === 'source') { const cistern = createCisternModel(); cistern.position.set(p.x, 0, p.z); cistern.rotation.y = (1 - (Number(tile.rot) || 0)) * Math.PI / 2; this.levelGroup.add(cistern); } else if (tile.kind === 'flower' || tile.kind === 'sink') { const flower = createFlowerModel(tile, tile.kind === 'sink'); flower.position.set(p.x, 0, p.z); flower.userData.need = tile.need ?? 0; this.levelGroup.add(flower); this.flowerMeshes.set(this.fixedKey(tile.x, tile.z), flower); } else if (tile.kind === 'rock') { const rock = createRockModel(this.fixed.size); rock.position.set(p.x, 0, p.z); this.levelGroup.add(rock); } }
    this.syncBoard(board); this.markShadows(this.levelGroup);
  }
  syncBoard(board = []) { const entries = Array.isArray(board) ? board : []; const key = entries.map((item) => item ? `${item.kind}:${item.rot}` : '.').join('|'); if (key === this.signature && this.level) return; this.signature = key; this.pipeMeshes.forEach((pipe) => { this.levelGroup.remove(pipe); disposeModel(pipe); }); this.pipeMeshes.clear(); this.splitterMeshes.clear(); for (let z = 0; z < RULES.gridSize; z++) for (let x = 0; x < RULES.gridSize; x++) { const entry = entries[z * RULES.gridSize + x]; if (!entry || this.fixed.has(this.fixedKey(x, z))) continue; const dirs = ports(entry.kind, entry.rot); const pipe = createPipeModel(entry.kind, entry.rot, dirs); const p = gridWorld(x, z); pipe.position.set(p.x, 0, p.z); pipe.userData.gridX = x; pipe.userData.gridZ = z; this.levelGroup.add(pipe); this.pipeMeshes.set(this.fixedKey(x, z), pipe); if (entry.kind === 'splitter') this.splitterMeshes.set(this.fixedKey(x, z), pipe); this.markShadows(pipe); } }
  updateFlowers(run) { const received = run?.received || {}; this.flowerMeshes.forEach((flower, key) => { const [x, z] = key.split(',').map(Number); const count = Number(received[indexOf(x, z)] || 0); const need = Number(flower.userData.need || 0); const progress = need ? clamp(count / need, 0, 1) : 0; flower.children.forEach((child) => { if (child.name.startsWith('petal-')) child.rotation.x = progress * .65; }); const ring = flower.getObjectByName('quota-ring'); if (ring?.material) ring.material.emissiveIntensity = .3 + progress * .8; const canvas = flower.userData.quotaCanvas; const texture = flower.userData.quotaTexture; const value = `${count}/${need}`; if (canvas && texture && flower.userData.quotaValue !== value) { const ctx = canvas.getContext('2d'); ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = 'rgba(17,39,53,.88)'; ctx.roundRect(2, 2, 124, 44, 10); ctx.fill(); ctx.fillStyle = '#f7d58b'; ctx.font = 'bold 25px sans-serif'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText(value, 64, 24); texture.needsUpdate = true; flower.userData.quotaValue = value; } }); }
  syncPackets(run, dt) { const packets = Array.isArray(run?.packets) ? run.packets : []; const live = new Set(); const fraction = clamp(Number(run?.clock || 0) / Math.max(.001, Number(RULES.tickSeconds) || .32), 0, 1); for (const packet of packets) { const id = packet.id; live.add(id); let mesh = this.packetMeshes.get(id); if (!mesh || mesh.userData.mask !== packet.mask) { if (mesh) { this.world.remove(mesh); disposeModel(mesh); } mesh = createPacketModel(packet.mask); mesh.userData.mask = packet.mask; this.world.add(mesh); this.packetMeshes.set(id, mesh); }
      const direction = dirVector(packet.dir);
      const current = run.board[indexOf(packet.x, packet.z)];
      const nextX = packet.x + direction.x, nextZ = packet.z + direction.z;
      const next = run.board[indexOf(nextX, nextZ)];
      let tile, incoming, outgoing, progress, center;
      if (fraction < .5) {
        tile = current; outgoing = packet.dir;
        incoming = tile?.kind === 'elbow' ? ports(tile.kind, tile.rot).find(port => port !== outgoing) : tile?.kind === 'splitter' ? (tile.rot + 2) % 4 : (outgoing + 2) % 4;
        progress = .5 + fraction; center = gridWorld(packet.x, packet.z);
      } else {
        tile = next; incoming = (packet.dir + 2) % 4;
        outgoing = tile?.kind === 'elbow' ? ports(tile.kind, tile.rot).find(port => port !== incoming) : packet.dir;
        progress = fraction - .5; center = gridWorld(nextX, nextZ);
      }
      const point = routePoint(tile?.kind || 'straight', incoming, outgoing, progress);
      mesh.position.set(center.x + point.x, point.y + .03, center.z + point.z);
      if (dt > 0) mesh.rotation.y += dt * 3; }
    this.packetMeshes.forEach((mesh, id) => { if (!live.has(id)) { this.world.remove(mesh); disposeModel(mesh); this.packetMeshes.delete(id); } }); }
  syncSplitters(run) { const counts = run?.splitCounts || {}; this.splitterMeshes.forEach((splitter, key) => { const [x, z] = key.split(',').map(Number); const rotor = splitter.getObjectByName('splitter-rotor'); if (rotor) pointSplitter(splitter, Number(counts[indexOf(x, z)]) || 0); }); }
  spawnEffect(event) { const color = event.type === 'receive' || event.type === 'tint' ? palette.gold : event.type === 'leak' ? palette.red : palette.glass; const ring = new THREE.Mesh(new THREE.TorusGeometry(.16, .025, 6, 16), new THREE.MeshBasicMaterial({ color, transparent: true, opacity: .8 })); ring.rotation.x = Math.PI / 2; const p = gridWorld(Number(event.x) || 0, Number(event.z) || 0); ring.position.set(p.x, .3, p.z); this.world.add(ring); this.effects.push({ root: ring, age: 0 }); }
  processEvents(view) { const events = Array.isArray(view?.events) ? view.events : []; if (!events.length || events === this.lastEvents) return; this.lastEvents = events; events.forEach((event) => { if (['place', 'tint', 'receive', 'leak', 'split'].includes(event.type)) this.spawnEffect(event); }); }
  updateEffects(dt) { if (dt <= 0) return; for (let i = this.effects.length - 1; i >= 0; i--) { const effect = this.effects[i]; effect.age += dt; effect.root.scale.setScalar(1 + effect.age * 2); effect.root.material.opacity = Math.max(0, .8 - effect.age * 1.5); if (effect.age > .55) { this.world.remove(effect.root); disposeModel(effect.root); this.effects.splice(i, 1); } } }
  setGhost(ghost, x, z, invalid = false, visible = true) { const p = gridWorld(x, z); ghost.position.set(p.x, .03, p.z); ghost.visible = visible && !invalid && x >= 0 && x < RULES.gridSize && z >= 0 && z < RULES.gridSize; ghost.traverse((object) => { if (object.isMesh) { object.material.color.set(invalid ? palette.red : palette.gold); object.material.emissive?.set(invalid ? palette.red : palette.gold); } }); }
  syncCursor(view, run) { const editing = run?.status === 'edit'; const cursor = view?.cursor; const tool = view?.tool || 'straight'; const rotation = Number(view?.rotation) || 0; if (this.cursorOutline) { this.cursorOutline.visible = !!editing && !!cursor; if (cursor) { const p = gridWorld(cursor.x, cursor.z); this.cursorOutline.position.set(p.x, 0, p.z); } } if (cursor && (!this.cursorGhost || this.cursorGhost.userData.kind !== tool || this.cursorGhost.userData.rotation !== rotation)) { if (this.cursorGhost) { this.world.remove(this.cursorGhost); disposeModel(this.cursorGhost); } const dirs = ports(tool, rotation); this.cursorGhost = createCursorModel(tool, rotation, dirs); this.cursorGhost.userData.kind = tool; this.cursorGhost.userData.rotation = rotation; this.world.add(this.cursorGhost); } if (this.cursorGhost && cursor) this.setGhost(this.cursorGhost, cursor.x, cursor.z, this.fixed.has(this.fixedKey(cursor.x, cursor.z)), editing); const hint = editing ? view?.hint : null; if (hint && (!this.hintGhost || this.hintGhost.userData.kind !== hint.kind || this.hintGhost.userData.rotation !== hint.rot)) { if (this.hintGhost) { this.world.remove(this.hintGhost); disposeModel(this.hintGhost); } this.hintGhost = createCursorModel(hint.kind, hint.rot, ports(hint.kind, hint.rot)); this.hintGhost.userData.kind = hint.kind; this.hintGhost.userData.rotation = hint.rot; this.world.add(this.hintGhost); } if (this.hintGhost && hint) this.setGhost(this.hintGhost, hint.x, hint.z, false, true); if (!hint && this.hintGhost) { this.world.remove(this.hintGhost); disposeModel(this.hintGhost); this.hintGhost = null; } }
  update(run = null, dt = 1 / 60, view = {}) { const delta = clamp(Number(dt) || 0, 0, .25); if (delta > 0) this.elapsed += delta; const levelId = run?.levelId || view?.levelId; if (levelId && levelId !== this.levelId) this.buildLevel(levelId, run?.board); else if (this.level) this.syncBoard(run?.board); this.updateFlowers(run); this.syncPackets(run, delta); this.syncSplitters(run); this.syncCursor(view, run); this.processEvents(view); this.updateEffects(delta); if (!this.software && this.keyLight && run?.packets?.[0]) { const packet = run.packets[0]; const p = gridWorld(packet.x, packet.z); this.keyLight.position.set(p.x + 7, 13, p.z + 8); this.keyLight.target.position.set(p.x, 0, p.z); this.keyLight.target.updateMatrixWorld(); } this.renderer.render(this.scene, this.camera); this.frame++; }
  resize() { const width = this.canvas.clientWidth || this.host?.clientWidth || 640; const height = this.canvas.clientHeight || this.host?.clientHeight || 640; const aspect = width / Math.max(1, height); this.camera.left = -aspect / 2; this.camera.right = aspect / 2; this.camera.top = .5; this.camera.bottom = -.5; this.camera.position.set(9, 15, 11); this.camera.lookAt(0, 0, 0); this.camera.updateProjectionMatrix(); this.camera.updateMatrixWorld(true); const corners = [-4.9, 4.9].flatMap((x) => [-4.9, 4.9].map((z) => new THREE.Vector3(x, .03, z))); const extent = corners.reduce((max, point) => { const projected = point.clone().project(this.camera); return Math.max(max, Math.abs(projected.x), Math.abs(projected.y)); }, 0); const frustumHeight = Math.max(12, extent / .82); this.renderer.setPixelRatio(Math.min(2, globalThis.devicePixelRatio || 1, Math.sqrt(this.pixelBudget / Math.max(1, width * height)))); this.renderer.setSize(width, height, false); this.camera.left = -frustumHeight * aspect / 2; this.camera.right = frustumHeight * aspect / 2; this.camera.top = frustumHeight / 2; this.camera.bottom = -frustumHeight / 2; this.camera.updateProjectionMatrix(); this.camera.updateMatrixWorld(true); }
  pick(clientX, clientY) { const rect = this.canvas.getBoundingClientRect(); const nx = ((clientX - rect.left) / Math.max(1, rect.width)) * 2 - 1; const ny = -((clientY - rect.top) / Math.max(1, rect.height)) * 2 + 1; const raycaster = new THREE.Raycaster(); raycaster.setFromCamera(new THREE.Vector2(nx, ny), this.camera); const plane = new THREE.Plane(new THREE.Vector3(0, 1, 0), 0); const point = new THREE.Vector3(); if (!raycaster.ray.intersectPlane(plane, point)) return null; const x = Math.round(point.x / RULES.cellSize + 3); const z = Math.round(point.z / RULES.cellSize + 3); return x >= 0 && x < RULES.gridSize && z >= 0 && z < RULES.gridSize ? { x, z } : null; }
  project(x, z) { const p = gridWorld(x, z); const projected = new THREE.Vector3(p.x, .03, p.z).project(this.camera); const rect = this.canvas.getBoundingClientRect(); return { x: rect.left + (projected.x + 1) * rect.width / 2, y: rect.top + (1 - projected.y) * rect.height / 2 }; }
  get stats() { const info = this.renderer.info; return { software: this.software, pixels: (this.canvas.width || 0) * (this.canvas.height || 0), frames: this.frame, drawCalls: info.render.calls, triangles: info.render.triangles, geometries: info.memory.geometries, levelId: this.levelId }; }
  dispose() { this.resizeObserver?.disconnect(); this.resizeObserver = null; this.effects.forEach((effect) => disposeModel(effect.root)); this.effects.length = 0; this.packetMeshes.forEach((mesh) => disposeModel(mesh)); this.packetMeshes.clear(); disposeModel(this.world); this.skyTexture?.dispose(); this.renderer.dispose(); }
}

export function createScene(host) { return new RainScene(host); }
export default createScene;
